// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICarbonStar: typeof import('~icons/carbon/star')['default']
    IIcAlert: typeof import('~icons/ic/alert')['default']
    IIcBaselineDesktopMac: typeof import('~icons/ic/baseline-desktop-mac')['default']
    IIcClose: typeof import('~icons/ic/close')['default']
    IIcMenu: typeof import('~icons/ic/menu')['default']
    IIcRoundAccountCircle: typeof import('~icons/ic/round-account-circle')['default']
    IIcRoundDarkMode: typeof import('~icons/ic/round-dark-mode')['default']
    IIcRoundEmail: typeof import('~icons/ic/round-email')['default']
    IIcRoundLightMode: typeof import('~icons/ic/round-light-mode')['default']
    IIcRoundNotifications: typeof import('~icons/ic/round-notifications')['default']
    IIcRoundSearch: typeof import('~icons/ic/round-search')['default']
    IIcRoundSettings: typeof import('~icons/ic/round-settings')['default']
    IIcSharpArrowDropDown: typeof import('~icons/ic/sharp-arrow-drop-down')['default']
    IIcSharpArrowDropUp: typeof import('~icons/ic/sharp-arrow-drop-up')['default']
    IIcSharpModeNight: typeof import('~icons/ic/sharp-mode-night')['default']
    IIcTwotoneChevronDown: typeof import('~icons/ic/twotone-chevron-down')['default']
    IIcTwotoneChevronRight: typeof import('~icons/ic/twotone-chevron-right')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiAlert: typeof import('~icons/mdi/alert')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMoonWaxingCrescent: typeof import('~icons/mdi/moon-waxing-crescent')['default']
    IMdiMoonWaxingIMdiMoonWaxingCrescent: typeof import('~icons/mdi/moon-waxing-i-mdi-moon-waxing-crescent')['default']
    IMdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
