// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonStar: typeof import('~icons/carbon/star')['default']
    IIcBaselineDesktopMac: typeof import('~icons/ic/baseline-desktop-mac')['default']
    IIcClose: typeof import('~icons/ic/close')['default']
    IIcMenu: typeof import('~icons/ic/menu')['default']
    IIcRoundAccountCircle: typeof import('~icons/ic/round-account-circle')['default']
    IIcRoundDarkMode: typeof import('~icons/ic/round-dark-mode')['default']
    IIcRoundEmail: typeof import('~icons/ic/round-email')['default']
    IIcRoundLightMode: typeof import('~icons/ic/round-light-mode')['default']
    IIcRoundNotifications: typeof import('~icons/ic/round-notifications')['default']
    IIcRoundSearch: typeof import('~icons/ic/round-search')['default']
    IIcRoundSettings: typeof import('~icons/ic/round-settings')['default']
    IIcSharpArrowDropDown: typeof import('~icons/ic/sharp-arrow-drop-down')['default']
    IIcSharpArrowDropUp: typeof import('~icons/ic/sharp-arrow-drop-up')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMoonWaxingCrescent: typeof import('~icons/mdi/moon-waxing-crescent')['default']
    IMdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
